export default [
    "Overwatch",
    "Fortnite",
    "Apex Legends",
    "Rocket League",
    "League of Legends",
    "Valorant",
    "CS:GO",
    "Rainbow Six Siege",
    "Call of Duty",
    "Hearthstone",
    "Dota 2",
    "Starcraft 2",
    "World of Warcraft",
    "FIFA",
    "NBA 2K",
    "Madden NFL",
    "NHL",
    "Super Smash Bros",
    "Street Fighter",
    "Tekken",
    "Mortal Kombat",
    "PUBG",
    "Paladins",
    "Heroes of the Storm",
    "Clash Royale",
    "Clash of Clans",
    "Brawl Stars",
    "Teamfight Tactics",
  ];